import { LocalizedFAQ } from "@/@types/metadata";

export const quizPlayerFAQ: LocalizedFAQ = {
  en: [
    {
      question: "What is a quiz player?",
      answer:
        "A quiz player is a tool that lets you play and answer quizzes directly in your browser. It allows you to practice multiple-choice questions without logging in or installing any app.",
    },
    {
      question: "Do I need to create an account to play a quiz?",
      answer:
        "No. The quiz player works entirely in your browser and does not require registration or login.",
    },
    {
      question: "How do I load a quiz into the quiz player?",
      answer:
        "You can load a quiz by uploading a quiz data file generated by Flowtooly Quiz Maker. The quiz will be ready to play instantly after import.",
    },
    {
      question: "Are quiz answers and results saved?",
      answer:
        "No. All quiz data, answers, and results are processed locally in your browser and are not stored on any server.",
    },
    {
      question: "Does the quiz player support timers and shuffled questions?",
      answer:
        "Yes. The quiz player supports time limits, question shuffling, and option shuffling, depending on the quiz configuration.",
    },
    {
      question: "Who is this quiz player suitable for?",
      answer:
        "This tool is suitable for students, teachers, trainers, and anyone who wants to practice quizzes quickly without complex setup.",
    },
  ],

  id: [
    {
      question: "Apa itu quiz player?",
      answer:
        "Quiz player adalah alat untuk memainkan dan mengerjakan kuis langsung di browser. Alat ini memungkinkan latihan soal pilihan ganda tanpa login atau instalasi aplikasi.",
    },
    {
      question: "Apakah saya perlu akun untuk memainkan kuis?",
      answer:
        "Tidak. Quiz player ini berjalan sepenuhnya di browser dan tidak memerlukan login atau pendaftaran.",
    },
    {
      question: "Bagaimana cara memasukkan kuis ke quiz player?",
      answer:
        "Anda dapat memasukkan kuis dengan mengunggah file data kuis yang dibuat menggunakan Flowtooly Quiz Maker. Kuis akan langsung siap dimainkan.",
    },
    {
      question: "Apakah jawaban dan hasil kuis disimpan?",
      answer:
        "Tidak. Semua data kuis, jawaban, dan hasil diproses secara lokal di browser dan tidak disimpan di server.",
    },
    {
      question: "Apakah quiz player mendukung timer dan soal acak?",
      answer:
        "Ya. Quiz player mendukung batas waktu, pengacakan soal, dan pengacakan pilihan jawaban sesuai konfigurasi kuis.",
    },
    {
      question: "Siapa yang cocok menggunakan quiz player ini?",
      answer:
        "Alat ini cocok untuk pelajar, guru, trainer, maupun siapa saja yang ingin latihan soal dengan cepat tanpa konfigurasi rumit.",
    },
  ],
};

export default quizPlayerFAQ;
