import { LocalizedFAQ } from "@/@types/metadata";

export const qrGeneratorFAQ: LocalizedFAQ = {
  en: [
    {
      question: "What is a QR code?",
      answer:
        "A QR code (Quick Response code) is a type of two-dimensional barcode that can store text, URLs, and other data.\n\n" +
        "Learn more:\n" +
        "- [Wikipedia – QR code](https://en.wikipedia.org/wiki/QR_code)",
    },
    {
      question: "What can I use a QR generator for?",
      answer:
        "QR codes are commonly used for sharing website links, contact information, Wi-Fi access, menus, and printed materials.",
    },
    {
      question: "Are the generated QR codes static or dynamic?",
      answer:
        "The QR codes generated by this tool are static, meaning the encoded data cannot be changed after creation.",
    },
    {
      question: "Can I use the QR code for printing or sharing?",
      answer:
        "Yes. Generated QR codes can be downloaded and used for printing, posters, packaging, or digital sharing.",
    },
    {
      question: "Is this QR generator safe to use?",
      answer:
        "Yes. All QR code generation is performed locally in your browser. No data is uploaded or stored on any server.",
    },
    {
      question: "Who should use a QR generator?",
      answer:
        "This tool is useful for businesses, educators, event organizers, and anyone who needs to share information quickly via QR codes.",
    },
  ],

  id: [
    {
      question: "Apa itu QR code?",
      answer:
        "QR code (Quick Response code) adalah jenis barcode dua dimensi yang dapat menyimpan teks, URL, dan data lainnya.\n\n" +
        "Bacaan lanjutan:\n" +
        "- [Wikipedia – QR code](https://en.wikipedia.org/wiki/QR_code)",
    },
    {
      question: "Untuk apa QR generator digunakan?",
      answer:
        "QR code sering digunakan untuk membagikan link website, informasi kontak, akses Wi-Fi, menu, dan media cetak.",
    },
    {
      question: "Apakah QR code yang dihasilkan bersifat statis atau dinamis?",
      answer:
        "QR code yang dihasilkan bersifat statis, artinya data di dalamnya tidak bisa diubah setelah dibuat.",
    },
    {
      question: "Apakah QR code bisa digunakan untuk cetak atau dibagikan?",
      answer:
        "Ya. QR code dapat diunduh dan digunakan untuk keperluan cetak maupun dibagikan secara digital.",
    },
    {
      question: "Apakah QR generator ini aman digunakan?",
      answer:
        "Ya. Semua proses pembuatan QR dilakukan langsung di browser tanpa mengunggah atau menyimpan data ke server.",
    },
    {
      question: "Siapa yang cocok menggunakan QR Generator?",
      answer:
        "Alat ini cocok untuk bisnis, pendidik, penyelenggara acara, dan siapa pun yang perlu membagikan informasi secara cepat melalui QR code.",
    },
  ],
};

export default qrGeneratorFAQ;
