import { SEO_CONFIG } from "@/constants/seo";
import { Locale, useLocale } from "next-intl";
import * as XLSX from "xlsx";

const now = new Date();

const brandMapping: Record<Locale, string[][]> = {
  en: [
    ["Flowtooly Report"],
    ["Utility Tools for Everyday Needs"],
    [],
    ["Report Information"],
    ["Generated By", "Flowtooly"],
    ["Generated At", now.toLocaleString("en-US")],
    ["Language", "English (en-US)"],
    ["Timezone", "GMT+7"],
    ["Website", SEO_CONFIG.siteUrl],
    [],
    ["Data Disclaimer"],
    ["• This report is generated automatically by Flowtooly."],
    ["• The accuracy depends on the data provided by the user."],
    ["• This report is for informational purposes only."],
  ],
  id: [
    ["Laporan Flowtooly"],
    ["Tools Utilitas Online untuk Kebutuhan Sehari-hari"],
    [],
    ["Informasi Laporan"],
    ["Dibuat Oleh", "Flowtooly"],
    ["Waktu Pembuatan", now.toLocaleString("id-ID")],
    ["Bahasa", "Indonesia (id-ID)"],
    ["Zona Waktu", "GMT+7"],
    ["Situs Web", SEO_CONFIG.siteUrl],
    [],
    ["Catatan & Penyangkalan"],
    ["• Laporan ini dibuat secara otomatis oleh Flowtooly."],
    ["• Keakuratan data bergantung pada data yang dimasukkan oleh pengguna."],
    [
      "• Laporan ini bersifat informatif dan tidak dimaksudkan sebagai nasihat profesional.",
    ],
  ],
};

export function useExcelExport() {
  const locale = useLocale();

  const exportToExcel = <T extends object>(
    data: T[],
    fileName: string,
    header?: string[][]
  ) => {
    // Buat sheet
    const dataSheet = XLSX.utils.aoa_to_sheet(header ?? []);
    const brandSheet = XLSX.utils.aoa_to_sheet(brandMapping[locale]);
    
    const startRow = (header?.length ?? 0) + 1;

    XLSX.utils.sheet_add_json(dataSheet, data, {
      origin: { r: startRow, c: 0 },
      skipHeader: false,
    });

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, brandSheet, "Flowtooly");
    XLSX.utils.book_append_sheet(workbook, dataSheet, "Data");

    XLSX.writeFile(workbook, `${fileName}.xlsx`);
  };

  return {
    exportToExcel,
  };
}
