export const qrFAQ_id = [
  {
    question: "Apakah QR Code yang dibuat di Flowtooly aman?",
    answer:
      "Ya. Semua QR Code dibuat langsung di browser Anda. Tidak ada data yang dikirim atau disimpan di server Flowtooly, sehingga privasi Anda terjaga sepenuhnya.",
  },
  {
    question: "Apakah QR Code bisa kedaluwarsa?",
    answer:
      "Tidak. QR Code tidak akan kedaluwarsa kecuali link atau data tujuannya berubah atau tidak valid. Untuk QR statis dari Flowtooly, kode akan tetap valid selamanya.",
  },
  {
    question: "Apakah Flowtooly menyimpan QR Code atau data saya?",
    answer:
      "Tidak. Semua proses dilakukan secara lokal di browser Anda. Flowtooly tidak menyimpan teks, link, atau file apa pun yang Anda gunakan untuk membuat QR.",
  },
  {
    question: "Bisakah saya mencetak QR Code dengan kualitas tinggi?",
    answer:
      "Bisa. Flowtooly mendukung format SVG, PNG, JPEG, dan WEBP. Format SVG sangat direkomendasikan untuk keperluan cetak karena tidak pecah saat diperbesar.",
  },
  {
    question: "Jenis QR Code apa saja yang bisa dibuat?",
    answer:
      "Flowtooly mendukung URL, WiFi, Email, SMS, Event Calendar, Maps, Social Media, WhatsApp/Telegram, dan vCard. Jenis lain akan ditambahkan di masa depan.",
  },
  {
    question: "Apakah saya bisa menambahkan logo ke QR Code?",
    answer:
      "Bisa. Flowtooly memungkinkan Anda mengunggah atau memilih logo untuk jenis QR tertentu. Anda juga bisa mengatur ukuran logo, margin, dan background.",
  },
  {
    question: "Apakah menambahkan logo akan membuat QR sulit dipindai?",
    answer:
      "Secara umum, QR tetap dapat dipindai selama logo tidak menutupi pola titik penting. Flowtooly secara otomatis menjaga area aman agar QR tetap mudah dibaca.",
  },
  {
    question: "Format apa yang paling bagus untuk download QR Code?",
    answer:
      "SVG sangat ideal untuk cetakan atau desain profesional. PNG dan JPEG cocok untuk penggunaan digital. WEBP memberikan ukuran file lebih kecil dengan kualitas baik.",
  },
  {
    question: "Mengapa QR Code saya tidak bisa dipindai?",
    answer:
      "Pastikan kontras warna cukup tinggi, ukuran QR tidak terlalu kecil, dan link atau datanya benar. Hindari pola yang terlalu rumit terutama jika memakai logo.",
  },
];


export const qrFAQ_en = [
  {
    question: "Is the QR Code generated by Flowtooly safe?",
    answer:
      "Yes. All QR codes are generated locally in your browser. No data is uploaded or stored on Flowtooly’s servers, ensuring complete privacy.",
  },
  {
    question: "Will my QR Code expire?",
    answer:
      "No. A QR Code will never expire unless the destination link itself becomes invalid. For static QR Codes from Flowtooly, the code remains valid forever.",
  },
  {
    question: "Does Flowtooly store my QR Code or data?",
    answer:
      "No. Everything is processed locally in your browser. Flowtooly does not store any text, links, or media used to generate QR Codes.",
  },
  {
    question: "Can I print the QR Code in high resolution?",
    answer:
      "Yes. Flowtooly supports SVG, PNG, JPEG, and WEBP formats. SVG is recommended for high-resolution printing because it scales without losing quality.",
  },
  {
    question: "What types of QR Codes can I generate?",
    answer:
      "Flowtooly supports URL, WiFi, Email, SMS, Event Calendar, Maps, Social Media, WhatsApp/Telegram, and Contact vCard QR codes. More types will be added in the future.",
  },
  {
    question: "Can I add a logo to the QR Code?",
    answer:
      "Yes. Flowtooly allows you to upload or select logos for supported QR types. You can also adjust size, margin, and background settings.",
  },
  {
    question: "Will adding a logo affect QR Code readability?",
    answer:
      "Generally, QR Codes remain readable as long as the logo does not cover essential dot patterns. Flowtooly automatically maintains a safe margin around the logo.",
  },
  {
    question: "What is the best format to download a QR Code?",
    answer:
      "SVG format is ideal for printing or professional usage. PNG and JPEG are suitable for digital use. WEBP provides smaller file sizes with good quality.",
  },
  {
    question: "Why is my QR Code not scanning?",
    answer:
      "Make sure the contrast between the QR Code and background is high, the size is not too small, and the embedded link or data is valid. Avoid overly complex patterns when adding logos.",
  },
];
