/* eslint-disable jsx-a11y/alt-text */
import { Image, Text, View } from "@react-pdf/renderer";
import { headerStyles } from "../styles/header.styles";

interface Props {
  title: string;
  subtitle?: string;
}

export function PDFHeader({
  title,
  subtitle = "Generated by Flowtooly",
}: Props) {
  return (
    <View style={headerStyles.container} fixed>
      {/* Left: Logo */}
      <View style={headerStyles.logoWrapper}>

      <Image
        style={headerStyles.logo}
        source="/flowtooly/poster-bg-remove.png"
      />
      </View>

      {/* Right: Text */}
      <View style={headerStyles.textWrapper}>
        <Text style={headerStyles.brand}>Flowtooly</Text>
        <Text style={headerStyles.title}>{title}</Text>
        <Text style={headerStyles.subtitle}>{subtitle}</Text>
      </View>
    </View>
  );
}
