import {
  Document,
  ExternalHyperlink,
  Footer,
  Header,
  Packer,
  PageBreak,
  Paragraph,
  TextRun,
} from "docx";
import { useQuizMaker } from "../store/provider";
import { notNull } from "@/utils/type-guard/not-null";

export function useExportQuizDocx() {
  const { data } = useQuizMaker();

  /* ================= HEADER ================= */
  const header = new Header({
    children: [
      new Paragraph({
        children: [
          new TextRun({
            text: "Quiz Document · Generated with Flowtooly",
            italics: true,
          }),
        ],
      }),
    ],
  });

  /* ================= FOOTER ================= */
  const footer = new Footer({
    children: [
      new Paragraph({
        children: [
          new ExternalHyperlink({
            children: [
              new TextRun({
                text: "Generated by Flowtooly · Free Online Utility Tools",
                size: 20,
              }),
            ],
            link: "https://flowtooly.com",
          }),
        ],
      }),
    ],
  });

  /* ================= TITLE ================= */
  const titleSection = [
    new Paragraph({
      children: [
        new TextRun({
          text: data?.metadata.title ?? "Untitled",
          bold: true,
          size: 32,
        }),
      ],
      spacing: { after: 200 },
    }),

    data?.metadata.description
      ? new Paragraph({
          children: [
            new TextRun({
              text: data?.metadata.description,
              italics: true,
            }),
          ],
          spacing: { after: 400 },
        })
      : null,
  ].filter(notNull);

  const answerTitle = new Paragraph({
    children: [
      new PageBreak(),
      new TextRun({
        text: "ANSWER KEY",
        bold: true,
        size: 28,
      }),
    ],
    spacing: { after: 300 },
  });

  /* ================= QUESTIONS ================= */
  const questions = data?.questions.map((question, index) => {
    const questionNumber = new TextRun({
      text: `${index + 1}. `,
      bold: true,
    });

    const questionText = new TextRun({
      text: question.text,
      bold: true,
    });

    const options = question.options.map(
      (option) =>
        new TextRun({
          text: `${option.optionId}. ${option.text}`,
          break: 1,
        })
    );

    return new Paragraph({
      children: [questionNumber, questionText, ...options],
      spacing: { after: 300 },
    });
  });

  const answerParagraphs = data?.questions.map((question, index) => {
    return new Paragraph({
      children: [
        new TextRun({
          text: `${index + 1}. ${question.correctOptionId}`,
        }),
      ],
      spacing: { after: 120 },
    });
  });

  /* ================= DOCUMENT ================= */
  const doc = new Document({
    creator: "Flowtooly",
    lastModifiedBy: "Flowtooly",
    title: data?.metadata.title,
    description: data?.metadata.description,
    subject: "Quiz / Assessment Document",
    keywords: ["quiz", "assessment", "exam", "flowtooly"].join(", "),

    sections: [
      {
        headers: { default: header },
        footers: { default: footer },
        children: [
          ...titleSection,
          ...questions as Paragraph[],
          answerTitle,
          ...answerParagraphs as Paragraph[],
        ],
      },
    ],
  });

  /* ================= EXPORT ================= */
  const handleExportDocx = async () => {
    const blob = await Packer.toBlob(doc);
    const url = URL.createObjectURL(blob);

    const element = document.createElement("a");
    element.href = url;
    element.download = `${data?.metadata.title || "quiz"}.docx`;
    element.click();

    URL.revokeObjectURL(url);
  };

  return { handleExportDocx };
}
