"use client";

import { useLocale } from "next-intl";
import { toast } from "sonner";
import * as XLSX from "xlsx";
import { QuizMakerOutputData } from "../types/output";
import { SEO_CONFIG } from "@/constants/seo";
import { ToolName } from "@/@types/tools/index";
import { trackToolExport } from "@/utils/analytics/track-tool";

const TOOL_NAME: ToolName = "quiz-maker";

export function useExportQuizExcel() {
  const locale = useLocale();
  const now = new Date();

  const exportQuizExcel = (data: QuizMakerOutputData) => {
    if (data.questions.length === 0) {
      toast.error(
        locale === "en"
          ? "No questions available to export."
          : "Tidak ada pertanyaan untuk diekspor."
      );
      return;
    }

    // Sheet 1 — Brand
    const brandSheet = XLSX.utils.aoa_to_sheet([
      [locale === "id" ? "Laporan Flowtooly" : "Flowtooly Report"],
      ["Utility Tools for Everyday Needs"],
      [],
      ["Generated By", "Flowtooly"],
      [
        locale === "id" ? "Waktu Pembuatan" : "Generated At",
        now.toLocaleString(locale === "id" ? "id-ID" : "en-US"),
      ],
      ["Website", SEO_CONFIG.siteUrl],
    ]);

    // Sheet 2 — Quiz Info
    const infoSheet = XLSX.utils.aoa_to_sheet([
      [locale === "id" ? "Judul Quiz" : "Quiz Title", data.metadata.title],
      [
        locale === "id" ? "Deskripsi" : "Description",
        data.metadata.description,
      ],
      [],
      [
        locale === "id" ? "Acak Pertanyaan" : "Shuffle Questions",
        data.metadata.config.shuffleQuestions,
      ],
      [
        locale === "id" ? "Acak Opsi" : "Shuffle Options",
        data.metadata.config.shuffleOptions,
      ],
      [
        locale === "id"
          ? "Tampilkan Jawaban Benar"
          : "Reveal Correct Answer",
        data.metadata.config.revealCorrectAnswer,
      ],
      [
        locale === "id" ? "Batas Waktu (detik)" : "Time Limit (seconds)",
        data.metadata.config.timeLimitSeconds,
      ],
    ]);

    // Sheet 3 — Questions
    const questionRows = data.questions.map((q, index) => {
      const correct = q.options.find(
        (o) => o.optionId === q.correctOptionId
      );

      return {
        No: index + 1,
        Question: q.text,
        OptionA: q.options[0]?.text ?? "",
        OptionB: q.options[1]?.text ?? "",
        OptionC: q.options[2]?.text ?? "",
        OptionD: q.options[3]?.text ?? "",
        CorrectAnswer: correct?.text ?? "",
        Explanation: q.explanation,
      };
    });

    const questionSheet = XLSX.utils.json_to_sheet(questionRows);

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, brandSheet, "Flowtooly");
    XLSX.utils.book_append_sheet(workbook, infoSheet, "Quiz Info");
    XLSX.utils.book_append_sheet(workbook, questionSheet, "Questions");

    XLSX.writeFile(
      workbook,
      `${data.metadata.title} - Flowtooly.xlsx`
    );

    // 📊 Analytics
    trackToolExport(TOOL_NAME, "excel");

    toast.success(
      locale === "en"
        ? "Quiz exported successfully as Excel file."
        : "Quiz berhasil diekspor ke file Excel."
    );
  };

  return { exportQuizExcel };
}
